BEGIN;

CREATE TABLE IF NOT EXISTS "teacher"
(
    "teacher_id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"         varchar,
    "surname"      varchar,
    "patronymic"   varchar,
    "phone_number" varchar
);

CREATE TABLE IF NOT EXISTS "school_class"
(
    "class_id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "class_name" varchar,
    "teacher_id" bigint REFERENCES teacher (teacher_id)
);

CREATE TABLE IF NOT EXISTS "student"
(
    "student_id"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"           varchar,
    "surname"        varchar,
    "patronymic"     varchar,
    "date_of_birth"  DATE,
    "parent_contact" VARCHAR,
    "phone_number"   VARCHAR,
    "class_id"       bigint REFERENCES school_class (class_id)
);

CREATE TABLE IF NOT EXISTS "subject"
(
    "subject_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar
);

CREATE TABLE IF NOT EXISTS "daily_schedule"
(
    "daily_schedule_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date_day"          date,
    "class_id"          bigint REFERENCES school_class (class_id),
    "day_of_week"       varchar
);

CREATE TABLE IF NOT EXISTS "lesson"
(
    "lesson_id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "subject_id"        bigint REFERENCES subject (subject_id),
    "daily_schedule_id" bigint REFERENCES daily_schedule (daily_schedule_id),
    "lesson_number"     int
);

CREATE TABLE IF NOT EXISTS "mark"
(
    "mark_id"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "student_id" bigint REFERENCES student (student_id),
    "subject_id" bigint REFERENCES subject (subject_id),
    "lesson_id"  bigint REFERENCES lesson (lesson_id),
    "mark"       int,
    "grade_date" date
);

CREATE TABLE IF NOT EXISTS "homework"
(
    "homework_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "lesson_id"   bigint REFERENCES lesson (lesson_id),
    "description" text
);

COMMIT;