services:
  app:
    build:
      context: .  # Путь к директории с Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile
    ports:
      - "8080:8080"  # Проброс порта
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      - naumen_dairy
  postgresql:
    container_name: postgresql-school-dairy
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: school-dairy-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - naumen_dairy
  liquibase-migrations:
    container_name: school-dairy-db-migrations
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --search-path=/liquibase/changelog/
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/school-dairy-db
      - --username=postgres
      - --password=postgres
      - update
    #      - rollback
    #        - --tag=start
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - naumen_dairy

volumes:
  postgresql: { }

networks:
  naumen_dairy: { }