spring:
  application:
    name: Naumen_SchoolDairy

  datasource:
#    url: jdbc:postgresql://localhost:5434/school-dairy-db
    url: jdbc:postgresql://postgresql:5432/school-dairy-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        stringtype: unspecified

  jpa:
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${EMAIL}
    password: ${EMAILPASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    default-encoding: UTF-8

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}